import { getRoutes } from '@sencha/ext-web-components-router/dist/ext-router.component';
import '@sencha/ext-web-components/dist/ext-audio.component';
import '@sencha/ext-web-components/dist/ext-menu.component';
import '@sencha/ext-web-components/dist/ext-menuitem.component';
import '@sencha/ext-web-components/dist/ext-carousel.component';
import '@sencha/ext-web-components/dist/ext-button.component';
import '@sencha/ext-web-components/dist/ext-checkboxfield.component';
import '@sencha/ext-web-components/dist/ext-column.component';
import '@sencha/ext-web-components/dist/ext-comboboxfield.component';
import '@sencha/ext-web-components/dist/ext-container.component';
import '@sencha/ext-web-components/dist/ext-containerfield.component';
import '@sencha/ext-web-components/dist/ext-splitbutton.component';
import '@sencha/ext-web-components/dist/ext-dataview.component';
import '@sencha/ext-web-components/dist/ext-dialog.component';
import '@sencha/ext-web-components/dist/ext-datepanel.component';
import '@sencha/ext-web-components/dist/ext-datecolumn.component';
import '@sencha/ext-web-components/dist/ext-checkcolumn.component';
import '@sencha/ext-web-components/dist/ext-datepickerfield.component';
import '@sencha/ext-web-components/dist/ext-datepickernativefield.component';
import '@sencha/ext-web-components/dist/ext-emailfield.component';
import '@sencha/ext-web-components/dist/ext-fieldset.component';
import '@sencha/ext-web-components/dist/ext-filefield.component';
import '@sencha/ext-web-components/dist/ext-grid.component';
import '@sencha/ext-web-components/dist/ext-numberfield.component';
import '@sencha/ext-web-components/dist/ext-panel.component';
import '@sencha/ext-web-components/dist/ext-label.component';
import '@sencha/ext-web-components/dist/ext-passwordfield.component';
import '@sencha/ext-web-components/dist/ext-radiofield.component';
import '@sencha/ext-web-components/dist/ext-searchfield.component';
import '@sencha/ext-web-components/dist/ext-selectfield.component';
import '@sencha/ext-web-components/dist/ext-sliderfield.component';
import '@sencha/ext-web-components/dist/ext-spinnerfield.component';
import '@sencha/ext-web-components/dist/ext-tree.component';
import '@sencha/ext-web-components/dist/ext-treelist.component';
import '@sencha/ext-web-components/dist/ext-treelistitem.component';
import '@sencha/ext-web-components/dist/ext-panel.component';
import '@sencha/ext-web-components/dist/ext-segmentedbutton.component';
import '@sencha/ext-web-components/dist/ext-tabpanel.component';
import '@sencha/ext-web-components/dist/ext-tabbar.component';
import '@sencha/ext-web-components/dist/ext-tab.component';
import '@sencha/ext-web-components/dist/ext-textareafield.component';
import '@sencha/ext-web-components/dist/ext-textfield.component';
import '@sencha/ext-web-components/dist/ext-timefield.component';
import '@sencha/ext-web-components/dist/ext-textareafield.component';
import '@sencha/ext-web-components/dist/ext-textfield.component';
import '@sencha/ext-web-components/dist/ext-timefield.component';
import '@sencha/ext-web-components/dist/ext-timepanel.component';
import '@sencha/ext-web-components/dist/ext-titlebar.component';
import '@sencha/ext-web-components/dist/ext-togglefield.component';
import '@sencha/ext-web-components/dist/ext-toolbar.component';
import '@sencha/ext-web-components/dist/ext-urlfield.component';
import '@sencha/ext-web-components/dist/ext-grid.component';
import '@sencha/ext-web-components/dist/ext-column.component';
import '@sencha/ext-web-components/dist/ext-formpanel.component';
import '@sencha/ext-web-components/dist/ext-textfield.component';
import '@sencha/ext-web-components/dist/ext-gauge.component';
import '@sencha/ext-web-components/dist/ext-colorselector.component';
import '@sencha/ext-web-components/dist/ext-draw.component';
import '@sencha/ext-web-components/dist/ext-progress.component';
import '@sencha/ext-web-components/dist/ext-spacer.component';
import '@sencha/ext-web-components/dist/ext-sheet.component';
import '@sencha/ext-web-components/dist/ext-video.component';
import '@sencha/ext-web-components/dist/ext-list.component';
import '@sencha/ext-web-components/dist/ext-widget.component';
import '@sencha/ext-web-components/dist/ext-nestedlist.component';
import '@sencha/ext-web-components/dist/ext-pivotgrid.component';
import '@sencha/ext-web-components/dist/ext-calendar.component';
import '@sencha/ext-web-components/dist/ext-calendar-list.component';
import '@sencha/ext-web-components/dist/ext-calendar-day.component';
import '@sencha/ext-web-components/dist/ext-calendar-days.component';
import '@sencha/ext-web-components/dist/ext-calendar-month.component';
import '@sencha/ext-web-components/dist/ext-calendar-week.component';
import '@sencha/ext-web-components/dist/ext-cartesian.component';
import '@sencha/ext-web-components/dist/ext-indicator.component';
import '@sencha/ext-web-components/dist/ext-lockedgrid.component';
import '@sencha/ext-web-components/dist/ext-tooltip.component';
import '@sencha/ext-web-components/dist/ext-polar.component';
import '@sencha/ext-web-components/dist/ext-chart.component';
import '@sencha/ext-web-components/dist/ext-widgetcell.component';
import '@sencha/ext-web-components/dist/ext-datecolumn.component';
import '@sencha/ext-web-components/dist/ext-textcolumn.component';
import '@sencha/ext-web-components/dist/ext-checkcolumn.component';
import '@sencha/ext-web-components/dist/ext-menucheckitem.component';
import '@sencha/ext-web-components/dist/ext-numbercolumn.component';
import '@sencha/ext-web-components/dist/ext-d3.component';
import '@sencha/ext-web-components/dist/ext-d3-horizontal-tree.component';
import '@sencha/ext-web-components/dist/ext-d3-pack.component';
import '@sencha/ext-web-components/dist/ext-d3-sunburst.component';
import '@sencha/ext-web-components/dist/ext-d3-tree.component';
import '@sencha/ext-web-components/dist/ext-d3-treemap.component';
import '@sencha/ext-web-components/dist/ext-pivotd3container.component';
import '@sencha/ext-web-components/dist/ext-chartnavigator.component';
import '@sencha/ext-web-components/dist/ext-d3-heatmap.component';
import '@sencha/ext-web-components/dist/ext-pivotheatmap.component';
import '@sencha/ext-web-components/dist/ext-checkboxgroup.component';
import '@sencha/ext-web-components/dist/ext-component.component';
import './Data.js';
import getMenu from './menu';
import MainComponent from './view/main/MainComponent.js';
import * as d3 from 'd3';

Ext.require([
    'Ext.layout.*',
    'Ext.data.TreeStore'
]);

function init() {
    window.d3 = d3;
    window.menu = getMenu();
    window.routes = getRoutes(window.menu);
    window.main = new MainComponent();
    document.body.innerHTML = window._code['main']['MainComponent.html'];
}

init();
