import { getRoutes } from '@sencha/ext-ewc-router/lib/ext-router.component';
import '@sencha/ext-ewc/lib/ext-audio.component';
import '@sencha/ext-ewc/lib/ext-menu.component';
import '@sencha/ext-ewc/lib/ext-menuitem.component';
import '@sencha/ext-ewc/lib/ext-carousel.component';
import '@sencha/ext-ewc/lib/ext-button.component';
import '@sencha/ext-ewc/lib/ext-checkboxfield.component';
import '@sencha/ext-ewc/lib/ext-column.component';
import '@sencha/ext-ewc/lib/ext-comboboxfield.component';
import '@sencha/ext-ewc/lib/ext-container.component';
import '@sencha/ext-ewc/lib/ext-containerfield.component';
import '@sencha/ext-ewc/lib/ext-splitbutton.component';
import '@sencha/ext-ewc/lib/ext-dataview.component';
import '@sencha/ext-ewc/lib/ext-dialog.component';
import '@sencha/ext-ewc/lib/ext-datepanel.component';
import '@sencha/ext-ewc/lib/ext-datecolumn.component';
import '@sencha/ext-ewc/lib/ext-checkcolumn.component';
import '@sencha/ext-ewc/lib/ext-datepickerfield.component';
import '@sencha/ext-ewc/lib/ext-datepickernativefield.component';
import '@sencha/ext-ewc/lib/ext-emailfield.component';
import '@sencha/ext-ewc/lib/ext-fieldset.component';
import '@sencha/ext-ewc/lib/ext-filefield.component';
import '@sencha/ext-ewc/lib/ext-grid.component';
import '@sencha/ext-ewc/lib/ext-numberfield.component';
import '@sencha/ext-ewc/lib/ext-panel.component';
import '@sencha/ext-ewc/lib/ext-label.component';
import '@sencha/ext-ewc/lib/ext-passwordfield.component';
import '@sencha/ext-ewc/lib/ext-radiofield.component';
import '@sencha/ext-ewc/lib/ext-searchfield.component';
import '@sencha/ext-ewc/lib/ext-selectfield.component';
import '@sencha/ext-ewc/lib/ext-sliderfield.component';
import '@sencha/ext-ewc/lib/ext-spinnerfield.component';
import '@sencha/ext-ewc/lib/ext-tree.component';
import '@sencha/ext-ewc/lib/ext-treelist.component';
import '@sencha/ext-ewc/lib/ext-treelistitem.component';
import '@sencha/ext-ewc/lib/ext-panel.component';
import '@sencha/ext-ewc/lib/ext-segmentedbutton.component';
import '@sencha/ext-ewc/lib/ext-tabpanel.component';
import '@sencha/ext-ewc/lib/ext-tabbar.component';
import '@sencha/ext-ewc/lib/ext-tab.component';
import '@sencha/ext-ewc/lib/ext-textareafield.component';
import '@sencha/ext-ewc/lib/ext-textfield.component';
import '@sencha/ext-ewc/lib/ext-timefield.component';
import '@sencha/ext-ewc/lib/ext-textareafield.component';
import '@sencha/ext-ewc/lib/ext-textfield.component';
import '@sencha/ext-ewc/lib/ext-timefield.component';
import '@sencha/ext-ewc/lib/ext-timepanel.component';
import '@sencha/ext-ewc/lib/ext-titlebar.component';
import '@sencha/ext-ewc/lib/ext-togglefield.component';
import '@sencha/ext-ewc/lib/ext-toolbar.component';
import '@sencha/ext-ewc/lib/ext-urlfield.component';
import '@sencha/ext-ewc/lib/ext-grid.component';
import '@sencha/ext-ewc/lib/ext-column.component';
import '@sencha/ext-ewc/lib/ext-formpanel.component';
import '@sencha/ext-ewc/lib/ext-textfield.component';
import '@sencha/ext-ewc/lib/ext-gauge.component';
import '@sencha/ext-ewc/lib/ext-colorselector.component';
import '@sencha/ext-ewc/lib/ext-draw.component';
import '@sencha/ext-ewc/lib/ext-progress.component';
import '@sencha/ext-ewc/lib/ext-spacer.component';
import '@sencha/ext-ewc/lib/ext-sheet.component';
import '@sencha/ext-ewc/lib/ext-video.component';
import '@sencha/ext-ewc/lib/ext-list.component';
import '@sencha/ext-ewc/lib/ext-widget.component';
import '@sencha/ext-ewc/lib/ext-nestedlist.component';
import '@sencha/ext-ewc/lib/ext-pivotgrid.component';
import '@sencha/ext-ewc/lib/ext-calendar.component';
import '@sencha/ext-ewc/lib/ext-calendar-list.component';
import '@sencha/ext-ewc/lib/ext-calendar-day.component';
import '@sencha/ext-ewc/lib/ext-calendar-days.component';
import '@sencha/ext-ewc/lib/ext-calendar-month.component';
import '@sencha/ext-ewc/lib/ext-calendar-week.component';
import '@sencha/ext-ewc/lib/ext-cartesian.component';
import '@sencha/ext-ewc/lib/ext-indicator.component';
import '@sencha/ext-ewc/lib/ext-lockedgrid.component';
import '@sencha/ext-ewc/lib/ext-tooltip.component';
import '@sencha/ext-ewc/lib/ext-polar.component';
import '@sencha/ext-ewc/lib/ext-chart.component';
import '@sencha/ext-ewc/lib/ext-widgetcell.component';
import '@sencha/ext-ewc/lib/ext-datecolumn.component';
import '@sencha/ext-ewc/lib/ext-textcolumn.component';
import '@sencha/ext-ewc/lib/ext-checkcolumn.component';
import '@sencha/ext-ewc/lib/ext-menucheckitem.component';
import '@sencha/ext-ewc/lib/ext-numbercolumn.component';
import '@sencha/ext-ewc/lib/ext-d3.component';
import '@sencha/ext-ewc/lib/ext-d3-horizontal-tree.component';
import '@sencha/ext-ewc/lib/ext-d3-pack.component';
import '@sencha/ext-ewc/lib/ext-d3-sunburst.component';
import '@sencha/ext-ewc/lib/ext-d3-tree.component';
import '@sencha/ext-ewc/lib/ext-d3-treemap.component';
import '@sencha/ext-ewc/lib/ext-pivotd3container.component';
import '@sencha/ext-ewc/lib/ext-chartnavigator.component';
import '@sencha/ext-ewc/lib/ext-d3-heatmap.component';
import '@sencha/ext-ewc/lib/ext-pivotheatmap.component';
import '@sencha/ext-ewc/lib/ext-checkboxgroup.component';
import '@sencha/ext-ewc/lib/ext-component.component';
import '@sencha/ext-ewc/lib/ext-breadcrumbbar.component';
import '@sencha/ext-ewc/lib/ext-froalaeditorfield.component';
import '@sencha/ext-ewc/lib/ext-accordion.component';

import './Data.js';
import getMenu from './menu';
import MainComponent from './view/main/MainComponent.js';
import * as d3 from 'd3';
import * as FroalaEditor from 'froala-editor/js/froala_editor.pkgd.min.js';

Ext.require([
    'Ext.layout.*',
    'Ext.data.TreeStore',
    'Ext.webcomponents.RendererCell'
]);

function init() {
    window.d3 = d3;
    window.FroalaEditor = FroalaEditor;
    window.menu = getMenu();
    window.routes = getRoutes(window.menu);
    window.main = new MainComponent();
    document.body.innerHTML = window._code['main']['MainComponent.html'];
}

init();
