rm -r ext-web-components/node_modules
rm -r ext-web-components-boilerplate/node_modules
rm -r ext-web-components-boilerplate-angular-cli/node_modules
rm -r ext-web-components-boilerplate-create-react-app/node_modules
rm -r ext-web-components-boilerplate-vue-cli/node_modules
rm -r ext-web-components-compress/node_modules
rm -r ext-web-components-conference-app/node_modules
rm -r ext-web-components-demo/node_modules
rm -r ext-web-components-demo-angular/node_modules
rm -r ext-web-components-demo-react/node_modules
rm -r ext-web-components-demo-vue/node_modules
rm -r ext-web-components-gen/node_modules
rm -r ext-web-components-kitchensink/node_modules
rm -r ext-web-components-renderercell/node_modules
rm -r ext-web-components-tests/node_modules